apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qn5ls7ko2-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qn5ls7ko2-java-quarkus-gitops